import Head from 'next/head'
import { AppLayout } from '@/components/layouts/AppLayout'

export default function Home() {
    return (
        <>
            <Head>
                <title>Task Manager</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppLayout>
                <div>index</div>
            </AppLayout>
        </>
    )
}
